name       : libqb
version    : 2.0.4
release    : 1
source     :
    - https://github.com/ClusterLabs/libqb/releases/download/v2.0.4/libqb-2.0.4.tar.gz : e3cf7e5018399d9ceb5a86f3f6ef7ed901cb7aae39c4fed4f647a7678d068f75
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libqb is a library providing high performance logging, tracing, ipc, and poll.
description: |
    libqb is a library with the primary purpose of providing high-performance, reusable features for client-server architecture, such as logging, tracing, inter-process communication (IPC), and polling. libqb is not intended to be an all-encompassing library, but instead provide focused APIs that are highly tuned for maximum performance for client-server applications.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(glib-2.0)
    - pkgconfig(libsystemd)
    - pkgconfig(libxml-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
