name       : libqb
version    : 2.0.8
release    : 3
source     :
    - https://github.com/ClusterLabs/libqb/releases/download/v2.0.8/libqb-2.0.8.tar.gz : 4832d0c1f12be38cbcf608585758d4a3124def253a3914b61afeebc68484311e
homepage   : http://clusterlabs.github.io/libqb/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : libqb is a library providing high performance logging, tracing, ipc, and poll
description: |
    libqb is a library with the primary purpose of providing high-performance, reusable features for client-server architecture, such as logging, tracing, inter-process communication (IPC), and polling. libqb is not intended to be an all-encompassing library, but instead provide focused APIs that are highly tuned for maximum performance for client-server applications.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(glib-2.0)
    - pkgconfig(libsystemd)
    - pkgconfig(libxml-2.0)
    - doxygen
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    rm -r $installdir/usr/share/doc
